trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  environment: 'dev'

stages:
- stage: Validate
  jobs:
  - job: TerraformCI
    steps:
    - task: UseTerraform@0
      inputs:
        terraformVersion: '1.5.0'
    - script: terraform init
      workingDirectory: terraform/
    - script: terraform validate
      workingDirectory: terraform/
    - script: terraform plan -out=tfplan
      workingDirectory: terraform/
