trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  environment: 'dev'

stages:
- stage: Validate
  jobs:
  - job: TerraformCI
    steps:
    - script: |
        echo "Installing unzip..."
        sudo apt-get update && sudo apt-get install -y unzip
        echo "Downloading Terraform..."
        curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        echo "Unzipping Terraform..."
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform --version
      displayName: 'Install Terraform'

    - script: terraform init
      workingDirectory: terraform/
      displayName: 'Terraform Init'

    - script: terraform validate
      workingDirectory: terraform/
      displayName: 'Terraform Validate'

    - script: terraform plan -out=tfplan
      workingDirectory: terraform/
      displayName: 'Terraform Plan'
