trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  environment: 'dev'

stages:
- stage: Deploy
  jobs:
  - job: TerraformCD
    steps:
    - task: UseTerraform@0
      inputs:
        terraformVersion: '1.5.0'
    - script: terraform init
      workingDirectory: terraform/
    - script: terraform apply -auto-approve
      workingDirectory: terraform/
